all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 100.127.80.27
          ansible_python_interpreter: /home/overtex/.ansible-venv/bin/python

    containers:
      hosts:
        prometheus-grafana:
          ansible_host: 192.168.1.101
        docker-registry:
          ansible_host: 192.168.1.102
        ci-runner:
          ansible_host: 192.168.1.103
      vars:
        ansible_user: root
    exporters:
      hosts:
        pi-host:
          ansible_host: 192.168.1.200
          ansible_user: overtex
          ansible_become: true
        pve-host:
          ansible_host: 100.127.80.27
          ansible_user: root
