lxc_template: "local:vztmpl/debian-12-standard_12.12-1_amd64.tar.zst"
lxc_storage: "local-lvm"
lxc_bridge: "vmbr0"
lxc_gateway: "192.168.1.1"

lxc_containers:
  - vmid: 101
    hostname: prometheus-grafana
    cores: 1
    memory: 768
    disk: 8
    ip: "192.168.1.101/24"
  - vmid: 102
    hostname: docker-registry
    cores: 1
    memory: 256
    disk: 8
    ip: "192.168.1.102/24"
  - vmid: 103
    hostname: ci-runner
    cores: 2
    memory: 1024
    disk: 12
    ip: "192.168.1.103/24"
